name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: use gcc-multilib
      run: sudo apt-get install gcc-multilib
    - name: create work dir && make
      run: |
        mkdir obj
        cd obj
        ../configure.rb -T linux_gcc
        make
